export const environment = {
  production: false,
  authDomain: 'dev-16fr5mnt2b0eess4.us.auth0.com',
  authClientId: '0qzqBCNnK3opV1kFcoYo57VrrxsogdOk',
  authAudience: 'https://finances-be.com/',
  baseUrl: 'http://localhost:8087/v2/',
};

export enum ApiEndpoints {
  wallets = 'wallets/',
  colors = 'colors/',
  currencies = 'currencies/',
  transactionCategories = 'transaction-categories/',
  icons = 'icons/',
  transactions = 'transactions/',
  stocks = 'stocks/',
  newsFilter = 'news-filters/',
  availableNewsLanguages = 'news-languages/',
  news = 'news/',
  stockChartData = 'stocks/chart-data/',
  topCategories = 'transaction-categories/top/',
  walletsBalance = 'wallets/chart-data/',
  transactionsAmount = 'transactions/chart-data/',
  ethKeys = 'eth-keys/',
  ethereumTransfer = 'eth-keys/transfer/',
  ethereumtransactions = 'eth-keys/transactions/',
  debts = 'debts/',
  debtPayment = 'debts/transactions/',
  userSettings = 'account-settings/',
  investments = 'investments/',
}
